codecov:
    require_ci_to_pass: yes

coverage:
    precision: 2
    round: down
    range: "90...100"

ignore:
    - "index.tsx"
    
status:
    project: yes
    patch: yes
    changes: no
    
comment:
    layout: "reach,diff,flags,tree"
    behavior: default
    require_changes: no

parsers:
    gcov:
        branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no